#!/usr/bin/env bash
#
# Generates markdown documentation files from example YAML files.
# Each YAML file in examples/<chain>/ becomes a markdown file in docs/04-examples/<chain>/
# Also generates the sidebar configuration for vitepress.
#

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "${SCRIPT_DIR}/../.." && pwd)"

EXAMPLES_DIR="${ROOT_DIR}/examples"
DOCS_EXAMPLES_DIR="${ROOT_DIR}/docs/04-examples"
VITEPRESS_DIR="${ROOT_DIR}/docs/.vitepress"
SIDEBAR_FILE="${VITEPRESS_DIR}/examples-sidebar.ts"

# Convert filename to title (e.g., "mainnet-fullnode" -> "Mainnet Fullnode")
filename_to_title() {
    local filename="$1"
    # Remove .yaml extension, replace hyphens/underscores with spaces, capitalize each word
    echo "$filename" | sed 's/\.yaml$//' | sed 's/[-_]/ /g' | awk '{for(i=1;i<=NF;i++) $i=toupper(substr($i,1,1)) tolower(substr($i,2))}1'
}

# Capitalize chain name (e.g., "nibiru" -> "Nibiru", "cosmoshub" -> "Cosmoshub")
capitalize_chain() {
    local chain="$1"
    echo "$chain" | awk '{print toupper(substr($0,1,1)) tolower(substr($0,2))}'
}

# Clean up existing docs examples
rm -rf "${DOCS_EXAMPLES_DIR:?}"/*

# Start building the sidebar config
{
    echo "// Auto-generated by contrib/scripts/generate-example-docs.sh"
    echo "// Do not edit manually."
    echo ""
    echo "export const examplesSidebar = ["
} > "$SIDEBAR_FILE"

first_chain=true

# Process each chain directory
for chain_dir in "${EXAMPLES_DIR}"/*/; do
    [ -d "$chain_dir" ] || continue

    chain_name=$(basename "$chain_dir")
    chain_title=$(capitalize_chain "$chain_name")
    docs_chain_dir="${DOCS_EXAMPLES_DIR}/${chain_name}"

    mkdir -p "$docs_chain_dir"

    # Add comma before chain entry (except first)
    if [ "$first_chain" = true ]; then
        first_chain=false
    else
        echo "," >> "$SIDEBAR_FILE"
    fi

    # Start chain sidebar entry
    {
        echo "  {"
        echo "    text: '${chain_title}',"
        echo "    base: '/04-examples/${chain_name}/',"
        echo "    items: ["
    } >> "$SIDEBAR_FILE"

    first_file=true

    # Process each YAML file in the chain directory
    for yaml_file in "${chain_dir}"*.yaml; do
        [ -f "$yaml_file" ] || continue

        filename=$(basename "$yaml_file")
        md_filename="${filename%.yaml}.md"
        link_name="${filename%.yaml}"

        file_title=$(filename_to_title "$filename")
        full_title="${chain_title} ${file_title}"

        # Generate markdown file
        {
            echo "# ${full_title}"
            echo ""
            echo '```yaml'
            cat "$yaml_file"
            echo ""
            echo '```'
        } > "${docs_chain_dir}/${md_filename}"

        echo "Generated: docs/04-examples/${chain_name}/${md_filename}"

        # Add comma before item (except first)
        if [ "$first_file" = true ]; then
            first_file=false
        else
            echo "," >> "$SIDEBAR_FILE"
        fi

        # Add sidebar item
        printf "      { text: '%s', link: '%s' }" "$file_title" "$link_name" >> "$SIDEBAR_FILE"
    done

    # Close chain sidebar entry
    {
        echo ""
        echo "    ]"
        printf "  }"
    } >> "$SIDEBAR_FILE"
done

# Close the sidebar array
{
    echo ""
    echo "];"
} >> "$SIDEBAR_FILE"

echo "Generated: docs/.vitepress/examples-sidebar.ts"
echo "Done generating example docs."
