FROM golang:1.21-alpine AS builder

WORKDIR /workspace
COPY go.mod go.sum* ./
RUN go mod download

# Copy the go source
COPY cmd/ cmd/
COPY api/ api/
COPY internal/ internal/
COPY pkg/ pkg/

RUN CGO_ENABLED=0 GOOS=linux go build -a -trimpath -o nodeutils ./cmd/nodeutils

FROM gcr.io/distroless/static
WORKDIR /
COPY --from=builder /workspace/nodeutils .

ENTRYPOINT ["/nodeutils"]
