FROM golang:1.21-alpine AS builder

WORKDIR /workspace
COPY go.mod go.sum* ./
RUN go mod download

# Copy the go source
COPY cmd/dataexporter cmd/dataexporter
COPY pkg/dataexporter pkg/dataexporter
COPY pkg/environ pkg/environ
COPY pkg/utils pkg/utils

RUN CGO_ENABLED=0 GOOS=linux go build -a -trimpath -o dataexporter ./cmd/dataexporter

FROM gcr.io/distroless/static
WORKDIR /
COPY --from=builder /workspace/dataexporter .

ENTRYPOINT ["/dataexporter"]
