FROM golang:1.21-alpine AS builder

WORKDIR /workspace
COPY go.mod go.sum* ./
RUN go mod download

# Copy the go source
COPY cmd/vault-token-renewer cmd/vault-token-renewer

RUN CGO_ENABLED=0 GOOS=linux go build -a -trimpath -o vault-token-renewer ./cmd/vault-token-renewer

FROM gcr.io/distroless/static
WORKDIR /
COPY --from=builder /workspace/vault-token-renewer .

ENTRYPOINT ["/vault-token-renewer"]
