FROM golang:1.24-alpine AS builder

WORKDIR /workspace
COPY go.mod go.sum* ./
COPY cmd/vault-token-renewer cmd/vault-token-renewer

RUN --mount=type=cache,target=/root/.cache/go-build \
    --mount=type=cache,target=/go/pkg/mod \
    CGO_ENABLED=0 GOOS=linux go build -a -trimpath -o vault-token-renewer ./cmd/vault-token-renewer

FROM gcr.io/distroless/static
WORKDIR /
COPY --from=builder /workspace/vault-token-renewer .

ENTRYPOINT ["/vault-token-renewer"]
