package v1

import (
	"context"
	"strings"
	"testing"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/types"
	"k8s.io/utils/ptr"
)

// chainNodeSetChildRef stamps the controller owner reference that IsControlledByChainNodeSet() keys
// off, marking a ChainNode as a generated ChainNodeSet member rather than a standalone create.
func chainNodeSetChildRef() []metav1.OwnerReference {
	return []metav1.OwnerReference{{
		APIVersion: GroupVersion.String(),
		Kind:       "ChainNodeSet",
		Name:       "some-set",
		UID:        types.UID("some-set-uid"),
		Controller: ptr.To(true),
	}}
}

// TestValidateCreateExemptsControlledChildren locks in that ChainNodes generated by a ChainNodeSet
// (e.g. "<set>-validator", or "<base>-<ordinal>" under a -signer/-cg/-seed group) are exempt from the
// reserved-name checks on create — the operator, not a user, produces those names.
func TestValidateCreateExemptsControlledChildren(t *testing.T) {
	for _, tc := range []struct {
		name  string
		child bool
		// reserved reports whether a standalone create of this name hits a reserved-name check.
		reserved bool
	}{
		{"some-set-validator", false, true},  // "-validator" reserved suffix
		{"some-set-validator", true, false},  // generated legacy validator child is exempt
		{"grp-signer-0", false, true},        // reserved StatefulSet-child shape
		{"grp-signer-0", true, false},        // scaled-up reserved-group child is exempt
		{"plain-node", false, false},         // ordinary standalone name is fine either way
	} {
		label := tc.name + "/standalone"
		if tc.child {
			label = tc.name + "/child"
		}
		t.Run(label, func(t *testing.T) {
			obj := &ChainNode{
				ObjectMeta: metav1.ObjectMeta{Name: tc.name, Namespace: "ns", UID: types.UID(tc.name + "-uid")},
			}
			if tc.child {
				obj.OwnerReferences = chainNodeSetChildRef()
			}
			_, err := (&ChainNode{}).ValidateCreate(context.Background(), obj)
			hitReserved := err != nil && strings.Contains(err.Error(), "is reserved")
			if tc.reserved && !hitReserved {
				t.Fatalf("%q must be rejected by the reserved-name check, got err=%v", tc.name, err)
			}
			if !tc.reserved && hitReserved {
				t.Fatalf("%q must not hit the reserved-name check, got %v", tc.name, err)
			}
		})
	}
}
