apiVersion: cosmopilot.voluzi.com/v1
kind: ChainNodeSet
metadata:
  name: cosmos-testnet
spec:
  app:
    image: ghcr.io/cosmos/gaia
    version: v25.2.0
    app: gaiad
    sdkVersion: v0.53

  validator:
    info:
      moniker: cosmopilot

    persistence:
      additionalVolumes:
        - name: wasm
          size: 1Gi
          path: /home/app/wasm
          deleteWithNode: true

    config:
      override:
        app.toml:
          minimum-gas-prices: 0.025uatom

    init:
      chainID: cosmoshub-testnet-0
      assets: ["1000000000000000000uatom"]
      stakeAmount: 100000000uatom
      minSelfDelegation: ""
      accountPrefix: cosmos
      valPrefix: cosmosvaloper
      additionalInitCommands:
        # Use uATOM as default denom
        - image: busybox
          command: [ "sh", "-c" ]
          args:
            - >
              sed -i 's/stake/uatom/g' /home/app/config/genesis.json;
              sed -i 's/uatomrs/stakers/g' /home/app/config/genesis.json;
              sed -i 's/uatomd/staked/g' /home/app/config/genesis.json;

  nodes:
    - name: fullnodes
      instances: 1

      config:
        override:
          app.toml:
            minimum-gas-prices: 0.025uatom
            pruning: custom
            pruning-keep-recent: "100"
            pruning-interval: "10"
