package resourcecleanup

import (
	"context"

	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/api/errors"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/types"
	"sigs.k8s.io/controller-runtime/pkg/client"
	"sigs.k8s.io/controller-runtime/pkg/controller/controllerutil"

	appsv1 "github.com/voluzi/cosmopilot/v2/api/v1"
)

const (
	// Finalizer keeps a controller root available until its attributed durable resources have reached
	// the requested retention or deletion state.
	Finalizer = "cosmopilot.voluzi.com/resource-cleanup"

	AnnotationRootOwnerAPIVersion = "cosmopilot.voluzi.com/root-owner-api-version"
	AnnotationRootOwnerKind       = "cosmopilot.voluzi.com/root-owner-kind"
	AnnotationRootOwnerName       = "cosmopilot.voluzi.com/root-owner-name"
	AnnotationRootOwnerNamespace  = "cosmopilot.voluzi.com/root-owner-namespace"
	AnnotationRootOwnerUID        = "cosmopilot.voluzi.com/root-owner-uid"
	AnnotationResourceClass       = "cosmopilot.voluzi.com/resource-class"
	AnnotationResourceOwnerUID    = "cosmopilot.voluzi.com/resource-owner-uid"
)

// ResourceClass identifies one deletion-policy field without relying on a generated resource name.
type ResourceClass string

const (
	ClassDataVolumes      ResourceClass = "dataVolumes"
	ClassGeneratedKeys    ResourceClass = "generatedKeys"
	ClassCosmosignerState ResourceClass = "cosmosignerState"
)

// RootOwner is the stable ChainNode or ChainNodeSet identity stamped on generated durable resources.
type RootOwner struct {
	APIVersion string
	Kind       string
	Name       string
	Namespace  string
	UID        types.UID
}

// RootOwnerFor resolves a generated ChainNode child to its controlling ChainNodeSet. Standalone
// ChainNodes and ChainNodeSets are their own cleanup root.
func RootOwnerFor(owner client.Object) RootOwner {
	if node, ok := owner.(*appsv1.ChainNode); ok {
		if controller := metav1.GetControllerOf(node); controller != nil &&
			controller.APIVersion == appsv1.GroupVersion.String() && controller.Kind == "ChainNodeSet" {
			return RootOwner{
				APIVersion: controller.APIVersion,
				Kind:       controller.Kind,
				Name:       controller.Name,
				Namespace:  node.GetNamespace(),
				UID:        controller.UID,
			}
		}
		return RootOwner{
			APIVersion: appsv1.GroupVersion.String(), Kind: "ChainNode", Name: node.GetName(),
			Namespace: node.GetNamespace(), UID: node.GetUID(),
		}
	}
	return RootOwner{
		APIVersion: appsv1.GroupVersion.String(), Kind: "ChainNodeSet", Name: owner.GetName(),
		Namespace: owner.GetNamespace(), UID: owner.GetUID(),
	}
}

// Stamp records durable attribution. Callers must use it only on resources they just created or
// whose existing controller ownership proves they were generated by Cosmopilot.
func Stamp(object metav1.Object, root RootOwner, class ResourceClass) bool {
	annotations := object.GetAnnotations()
	if annotations == nil {
		annotations = map[string]string{}
	}
	desired := map[string]string{
		AnnotationRootOwnerAPIVersion: root.APIVersion,
		AnnotationRootOwnerKind:       root.Kind,
		AnnotationRootOwnerName:       root.Name,
		AnnotationRootOwnerNamespace:  root.Namespace,
		AnnotationRootOwnerUID:        string(root.UID),
		AnnotationResourceClass:       string(class),
	}
	changed := false
	for key, value := range desired {
		if annotations[key] != value {
			annotations[key] = value
			changed = true
		}
	}
	if changed {
		object.SetAnnotations(annotations)
	}
	return changed
}

// StampResourceOwner records the immediate controller UID used when a ChainNodeSet child performs
// cleanup before the root-wide final pass.
func StampResourceOwner(object metav1.Object, ownerUID types.UID) bool {
	annotations := object.GetAnnotations()
	if annotations == nil {
		annotations = map[string]string{}
	}
	if annotations[AnnotationResourceOwnerUID] == string(ownerUID) {
		return false
	}
	annotations[AnnotationResourceOwnerUID] = string(ownerUID)
	object.SetAnnotations(annotations)
	return true
}

// IsAttributed reports whether object belongs to this exact root and resource class.
func IsAttributed(object metav1.Object, root RootOwner, class ResourceClass) bool {
	annotations := object.GetAnnotations()
	return annotations[AnnotationRootOwnerAPIVersion] == root.APIVersion &&
		annotations[AnnotationRootOwnerKind] == root.Kind &&
		annotations[AnnotationRootOwnerName] == root.Name &&
		annotations[AnnotationRootOwnerNamespace] == root.Namespace &&
		annotations[AnnotationRootOwnerUID] == string(root.UID) &&
		annotations[AnnotationResourceClass] == string(class)
}

// PrepareGeneratedResource stamps and controller-owns a newly generated resource. For an existing
// resource, it proceeds only when current controller ownership or stable root attribution proves the
// resource was generated by Cosmopilot; deterministic names alone never qualify.
func PrepareGeneratedResource(
	object client.Object,
	controller client.Object,
	scheme *runtime.Scheme,
	class ResourceClass,
	creating bool,
) (managed bool, changed bool, err error) {
	root := RootOwnerFor(controller)
	managed = creating || IsAttributed(object, root, class) || metav1.IsControlledBy(object, controller)
	if !managed {
		return false, false, nil
	}
	changed = Stamp(object, root, class)
	if StampResourceOwner(object, controller.GetUID()) {
		changed = true
	}
	if !metav1.IsControlledBy(object, controller) {
		if err := controllerutil.SetControllerReference(controller, object, scheme); err != nil {
			return false, changed, err
		}
		changed = true
	}
	return true, changed, nil
}

// FinalizeClass applies one deletion-policy class to every attributed object in the root namespace.
// Delete uses the UID read during classification as an API precondition and advances only after the
// object key is absent, so a same-name replacement is reclassified on the next pass. Retain removes
// only this controller's owner reference and requested Cosmopilot finalizers, leaving all unrelated
// owner references intact.
func FinalizeClass(
	ctx context.Context,
	c client.Client,
	root RootOwner,
	class ResourceClass,
	policy appsv1.DeletionPolicyType,
	controllerUID types.UID,
	ownedFinalizers ...string,
) (bool, error) {
	objects, err := listAttributed(ctx, c, root, class)
	if err != nil {
		return false, err
	}
	allDone := true
	for _, object := range objects {
		if controllerUID != root.UID && object.GetAnnotations()[AnnotationResourceOwnerUID] != string(controllerUID) {
			continue
		}
		switch policy {
		case appsv1.DeletionPolicyDelete:
			finalizerRemoved := false
			for _, finalizer := range ownedFinalizers {
				if controllerutil.ContainsFinalizer(object, finalizer) {
					controllerutil.RemoveFinalizer(object, finalizer)
					finalizerRemoved = true
				}
			}
			if finalizerRemoved {
				if err := c.Update(ctx, object); err != nil && !errors.IsNotFound(err) {
					return false, err
				}
				allDone = false
				continue
			}
			done, err := deleteExact(ctx, c, object)
			if err != nil {
				return false, err
			}
			allDone = allDone && done
		default:
			changed := removeMatchingControllerReference(object, controllerUID)
			for _, finalizer := range ownedFinalizers {
				if controllerutil.ContainsFinalizer(object, finalizer) {
					controllerutil.RemoveFinalizer(object, finalizer)
					changed = true
				}
			}
			if changed {
				if err := c.Update(ctx, object); err != nil && !errors.IsNotFound(err) {
					return false, err
				}
			}
		}
	}
	return allDone, nil
}

func listAttributed(ctx context.Context, c client.Client, root RootOwner, class ResourceClass) ([]client.Object, error) {
	objects := []client.Object{}
	switch class {
	case ClassGeneratedKeys:
		list := &corev1.SecretList{}
		if err := c.List(ctx, list, client.InNamespace(root.Namespace)); err != nil {
			return nil, err
		}
		for i := range list.Items {
			if IsAttributed(&list.Items[i], root, class) {
				objects = append(objects, &list.Items[i])
			}
		}
	default:
		list := &corev1.PersistentVolumeClaimList{}
		if err := c.List(ctx, list, client.InNamespace(root.Namespace)); err != nil {
			return nil, err
		}
		for i := range list.Items {
			if IsAttributed(&list.Items[i], root, class) {
				objects = append(objects, &list.Items[i])
			}
		}
	}
	return objects, nil
}

func deleteExact(ctx context.Context, c client.Client, object client.Object) (bool, error) {
	uid := object.GetUID()
	if object.GetDeletionTimestamp().IsZero() {
		if err := c.Delete(ctx, object, client.Preconditions{UID: &uid}); err != nil && !errors.IsNotFound(err) {
			return false, err
		}
	}
	current := object.DeepCopyObject().(client.Object)
	err := c.Get(ctx, client.ObjectKeyFromObject(object), current)
	if errors.IsNotFound(err) {
		return true, nil
	}
	if err != nil {
		return false, err
	}
	return false, nil
}

func removeMatchingControllerReference(object metav1.Object, controllerUID types.UID) bool {
	references := object.GetOwnerReferences()
	filtered := make([]metav1.OwnerReference, 0, len(references))
	changed := false
	for _, reference := range references {
		if reference.UID == controllerUID && reference.Controller != nil && *reference.Controller {
			changed = true
			continue
		}
		filtered = append(filtered, reference)
	}
	if changed {
		object.SetOwnerReferences(filtered)
	}
	return changed
}
