// Auto-generated by contrib/scripts/generate-example-docs.sh
// Do not edit manually.

export const examplesSidebar = [
  {
    text: 'Cosmoshub',
    base: '/04-examples/cosmoshub/',
    items: [
      { text: 'Mainnet Fullnode', link: 'mainnet-fullnode' },
      { text: 'Testnet With Fullnode', link: 'testnet-with-fullnode' }
    ]
  },
  {
    text: 'Nibiru',
    base: '/04-examples/nibiru/',
    items: [
      { text: 'Devnet With Fullnode', link: 'devnet-with-fullnode' },
      { text: 'Multi Validator Devnet', link: 'multi-validator-devnet' },
      { text: 'Nibid Init Tmkms', link: 'nibid_init_tmkms' }
    ]
  },
  {
    text: 'Osmosis',
    base: '/04-examples/osmosis/',
    items: [
      { text: 'Mainnet Fullnode', link: 'mainnet-fullnode' },
      { text: 'Testnet With Fullnode', link: 'testnet-with-fullnode' }
    ]
  }
];
