// Auto-generated by contrib/scripts/generate-example-docs.sh
// Do not edit manually.

export const examplesSidebar = [
  {
    text: 'Allora-network',
    base: '/04-examples/allora-network/',
    items: [
      { text: 'Mainnet Fullnode', link: 'mainnet-fullnode' },
      { text: 'Testnet With Fullnode', link: 'testnet-with-fullnode' }
    ]
  },
  {
    text: 'Cosmoshub',
    base: '/04-examples/cosmoshub/',
    items: [
      { text: 'Mainnet Fullnode', link: 'mainnet-fullnode' },
      { text: 'Testnet With Fullnode', link: 'testnet-with-fullnode' }
    ]
  },
  {
    text: 'Nibiru',
    base: '/04-examples/nibiru/',
    items: [
      { text: 'Mainnet Fullnode', link: 'mainnet-fullnode' },
      { text: 'Testnet With Fullnode', link: 'testnet-with-fullnode' }
    ]
  },
  {
    text: 'Osmosis',
    base: '/04-examples/osmosis/',
    items: [
      { text: 'Mainnet Fullnode', link: 'mainnet-fullnode' },
      { text: 'Testnet With Fullnode', link: 'testnet-with-fullnode' }
    ]
  }
];
