import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  cosmopilotSidebar: [
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: false,
      items: [
        'getting-started/prerequisites',
        'getting-started/chain-compatibility',
        'getting-started/installation',
        'getting-started/configuration',
        'getting-started/uninstall',
      ],
    },
    {
      type: 'category',
      label: 'Usage',
      collapsed: false,
      items: [
        'usage/deploy-node',
        'usage/deploy-node-set',
        'usage/genesis',
        'usage/node-config',
        'usage/persistence-and-backup',
        'usage/restoring-from-snapshot',
        'usage/exposing-endpoints',
        'usage/monitoring',
        'usage/upgrades',
        'usage/validator',
        'usage/initializing-new-network',
        'usage/tmkms',
        'usage/cosmoguard',
        'usage/cosmoseed',
        'usage/pod-disruption-budgets',
        'usage/vertical-pod-autoscaling',
      ],
    },
    {
      type: 'category',
      label: 'Operations',
      collapsed: false,
      items: [
        'operations/troubleshooting',
      ],
    },
    {
      type: 'category',
      label: 'Reference',
      collapsed: false,
      items: [
        'reference/architecture',
        {
          type: 'category',
          label: 'Custom Resource Definitions',
          collapsed: false,
          items: ['reference/crds/crds'],
        },
        'reference/cli',
        'reference/annotations',
      ],
    },
    'faq',
    {
      type: 'category',
      label: 'Examples',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'examples',
        },
      ],
    },
  ],
};

export default sidebars;
