apiVersion: cosmopilot.voluzi.com/v1
kind: ChainNodeSet
metadata:
  name: osmosis-devnet
spec:
  app:
    image: osmolabs/osmosis
    version: 31.0.0
    app: osmosisd
    sdkVersion: v0.45 # Old version of genesis commands

  validator:
    info:
      moniker: cosmopilot

    persistence:
      additionalVolumes:
        - name: wasm
          size: 1Gi
          path: /home/app/wasm
          deleteWithNode: true
        - name: ibc-08-wasm
          size: 1Gi
          path: /home/app/ibc_08-wasm
          deleteWithNode: true

    config:
      runFlags: ["--reject-config-defaults=true"]
      override:
        app.toml:
          minimum-gas-prices: 0.025uosmo

    init:
      chainID: osmosis-testnet-0
      accountPrefix: osmo
      valPrefix: osmovaloper
      assets: [ "100000000000000000000uosmo" ]
      stakeAmount: 100000000uosmo
      unbondingTime: 60s
      votingPeriod: 60s
      additionalInitCommands:
        # Use uOSMO as default denom
        - image: busybox
          command: [ "sh", "-c" ]
          args:
            - >
              sed -i 's/stake/uosmo/g' /home/app/config/genesis.json;
              sed -i 's/uosmors/stakers/g' /home/app/config/genesis.json;
              sed -i 's/uosmod/staked/g' /home/app/config/genesis.json;

  nodes:
    - name: fullnodes
      instances: 1

      persistence:
        additionalVolumes:
          - name: wasm
            size: 1Gi
            path: /home/app/wasm
            deleteWithNode: true
          - name: ibc-08-wasm
            size: 1Gi
            path: /home/app/ibc_08-wasm
            deleteWithNode: true

      config:
        runFlags: ["--reject-config-defaults=true"]
        override:
          app.toml:
            minimum-gas-prices: 0.025uosmo
