name: Test

on:
  push:
    paths-ignore:
      - 'docs/**'
      - '**/*.md'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Setup go
        uses: actions/setup-go@v7
        with:
          go-version-file: go.mod

      - name: Run Unit Tests
        run: make test.unit

      - name: Run Integration Tests
        run: make test.integration